version: '3.8'

services:
  nodejs:
    build: .
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/var/www
      - node_modules:/app/node_modules
    ports:
      - "7001:7001"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/letsencrypt/live/yourdomain.com
      - ./dhparam.pem:/etc/ssl/certs/dhparam.pem

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
