services:
  nodejs:
    build: .
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app/speech-server
      - node_modules:/app/speech-server/node_modules
    ports:
      - "7001:7001"

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=small
      - ASR_ENGINE=faster_whisper
      - ASR_QUANTIZATION=int8
      - OMP_NUM_THREADS=4
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1536M # Жесткий лимит ОЗУ, чтобы контейнер убивался до того, как повесит весь сервер

#  nginx:
#    image: nginx:alpine
#    restart: unless-stopped
#    networks:
#      - app-network
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /etc/letsencrypt/live/speech.krasterisk.ru:/etc/letsencrypt/live/speech.krasterisk.ru


volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
